# Generated by Django 4.0.6 on 2023-01-09 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Staff Product'},
        ),
    ]
